### ISSUE TITLE
[BUG] Andoird App crashes on weapon selection for T'au Commander in XV85 Battlesuit

### ISSUE THREAD

**Issue by ZaT** [KTManager/KTManagerApp#92] opened 2020-03-21 13:33 UTC
- Create T'au KillTeam
- Add "Commander in XV85 Enforced Battlesuit"
- Click "Change weapons" on this member

**Comment by lacombet** [comment] 2020-03-21 14:38
This is a duplicate of #93.
I added the Commander in XV85 Battlesuit in the list of concerned models.

**Closed as completed by lacombet** 2020-03-21 14:38 UTC
Labels: bug, duplicate
